### ISSUE TITLE
[Podcast] Boostagram

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#555] opened 2021-08-16 10:37 UTC
I'm not even sure how to spell this, or where to link to spec documentation of it... 

But afaik, in the TLV field of the payment, the sender can include a asci encoded message, with the time stamp and episode number, for every boost payment. This can then be extracted and read by the receiver / podcaster.

That's a super useful feature, and other 2.0 podcatchers have it implemented already. 

Maybe @daveajones & @adamc199 can provide more details / links?

**Comment by kingonly** [comment] 2021-08-16 10:40
We want to implement it soon.
It's a duplicate of #524...

**Closed by kingonly** 2021-08-16 10:40 UTC

**Comment by MaxHillebrand** [comment] 2021-08-16 10:47
Sorry for the duplicate then - I completely missed to search the repo - my bad...

**Comment by kingonly** [comment] 2021-08-16 10:47
No worries at all - thanks for pushing this 🙏
