### ISSUE TITLE
Podcast boost sometimes doesn't work and I see no notice

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#450] opened 2021-03-24 19:50 UTC
Hi,

Sometimes I try to boost and doesn't work and I see no notice.
Obs. Breez receive the fee but no sats is sent to podcast.

I think if the node is not working correctly, maybe the boost button should be disabled.

![photo_2021-03-24_16-48-50](https://user-images.githubusercontent.com/1178856/112374414-d4660f80-8cc0-11eb-8556-cb6aa14a2662.jpg)

**Comment by kingonly** [comment] 2021-09-09 10:27
Won't fix, by design

**Closed by kingonly** 2021-09-09 10:27 UTC
