### ISSUE TITLE
Lnurlw URLs passed via NFC are lower cased resulting in errors

### ISSUE THREAD

**Issue by blackcoffeexbt** [breez/breezmobile#949] opened 2022-07-20 22:19 UTC
Lnurlw addresses are typically case sensitive. It seems that breez is lower casing the URL before making the request to an lnurlw URL. This causes the response from the lnurlw to be an error as it does not exist. 

Screenshot showing lower cased lnurlw and GET response error is attached here. 

![Screenshot_20220720-231601](https://user-images.githubusercontent.com/87530449/180092122-49ed1692-1e95-4256-b397-fe3386b88789.png)

**Comment by kingonly** [comment] 2022-07-20 22:28
@blackcoffeexbt thanks for the report, we'll take a look. Do you have a test url we try in our tests to reproduce?

**Comment by kingonly** [comment] 2022-07-20 22:28
@ademar111190 please take a look

**Comment by blackcoffeexbt** [comment] 2022-07-21 09:43
> @blackcoffeexbt thanks for the report, we'll take a look. Do you have a test url we try in our tests to reproduce?

Thanks. Yes, you can use this as an example for testing.

lnurlw://sats.pw/withdraw/api/v1/lnurl/5NGw5bvHKudKNDWiaQeAai

**Comment by ademar111190** [comment] 2022-07-22 15:47
Let me share what I have discovered so far.

The point in the code where the URL is being converted to lower case is here https://github.com/fiatjaf/go-lnurl/blob/8690faff30d628a92b4f0257fdb3d1c3b50c200f/helpers.go#L15 it is being made by the go-lnurl library itself.

It is not an issue with others lnurlw's we have tested but this `sats.pw` seems to be case sensitive as you can see below comparing the curl with all lower case versus the original case:

```
Original case:
curl -X GET "https://sats.pw/withdraw/api/v1/lnurl/5NGw5bvHKudKNDWiaQeAai"
{"tag": "withdrawRequest", "callback": "https://sats.pw/withdraw/api/v1/lnurl/cb/5NGw5bvHKudKNDWiaQeAai", "k1": "XB3ayixmGphoxjErurPgNC", "minWithdrawable": 10000, "maxWithdrawable": 10000, "defaultDescription": "Gimmiw"}
```

```
Lower case:
curl -X GET "https://sats.pw/withdraw/api/v1/lnurl/5ngw5bvhkudkndwiaqeaai"
{"detail":"Withdraw link does not exist."}
```

So I don't know if we should change our code to not use the modified URL from go-lnurl lib or if `sats.pw` should ignore the case.

Please, let me know your thoughts about it @kingonly

**Comment by kingonly** [comment] 2022-07-22 18:01
To me it seems like a go-lnurl bug. @ademar111190 let's open a issue in the go-lnurl repo and see what fiatjaf says.

**Comment by ademar111190** [comment] 2022-07-25 21:39
I did open an issue to go-lnurl https://github.com/fiatjaf/go-lnurl/issues/9
As soon as we have a fix there, I'll apply the necessary changes on our side to solve this issue.

**Comment by ademar111190** [comment] 2022-07-26 16:24
The issue was fixed, to update that library and include the fix it is necessary to do some migrations. Roei is already working on it, so as soon as the library update enters to Breez lib plus this PR https://github.com/breez/breezmobile/pull/953 is merged we are going to have this issue fixed.

**Comment by kingonly** [comment] 2022-08-10 12:42
Fixed in latest

**Closed by kingonly** 2022-08-10 12:42 UTC
