### ISSUE TITLE
"Get refunds" page not showing all refunds?

### ISSUE THREAD

**Issue by orbitalturtle** [breez/breezmobile#1241] opened 2023-10-26 04:09 UTC
### General Description

Not sure if I'm reporting this to the correct repo, but -- I'm having a problem with the "get refunds" page. It's showing two refunds but I think there should be a couple more. (Didn't realize there was a max limit on transactions sent to the wallet so that's my bad oops :)) 

### How To Reproduce?

1. Click on the Get Refunds page.

### Operating System

Android 13

### Breez Version

Latest, Google Play

**Comment by ubbabeck** [comment] 2023-10-26 07:26
Hi @orbitalturtle,  sorry to hear this. Could you send us your logs to contact@breez.technology.

You may share your logs by doing the following.

1. Open side menu.
2. Select **Preferences --> Developers**
3. Select vertical **...** in top right corner --> **Share logs**.

**Comment by ubbabeck** [comment] 2023-11-02 08:26
Closing this now, but feel free to reopen if the issue isn't solved.

**Closed by ubbabeck** 2023-11-02 08:26 UTC
