### ISSUE TITLE
Filtering button not working in consistently

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1129] opened 2023-04-24 16:30 UTC
1. Open Podcast player
2. Open My Top Podcasts

The menu of options does not appear. It appears "show menu" which is wrong.
I do not know exactly how to reproduce this but it is not working consistently, most of the time it is working properly.

![image](https://user-images.githubusercontent.com/127208515/234059171-a12c59ad-caaf-4c45-9387-34729a3981ba.png)

**Comment by Nackoo2000** [comment] 2023-04-25 06:36
@roeierez figured it out when I hold the button for a bit this shows up. When I tap it works properly. Not sure if that is an issue at all. All other menu buttons behave the same way.

**Comment by ubbabeck** [comment] 2023-05-05 14:24
I think this is an issue with the [`PopUpMenuButton`](https://github.com/breez/breezmobile/blob/master/lib/routes/podcast_history/podcast_history.dart#L273) from [flutter](https://api.flutter.dev/flutter/material/PopupMenuButton-class.html)  and not caused by us as i were able to recreate this when testing with a unmodified `PopUpMenuButton`. 

I were not able to remove it on our app nor in the sample app. Do you know if there is an alternative menu button we may use or a way to remove this long press feature @erdemyerebasmaz ?

https://user-images.githubusercontent.com/36157890/236483344-ccc3d490-34d3-4a69-9ab5-d125d4118be5.mov

**Comment by ubbabeck** [comment] 2023-05-08 13:02
Erdem told me that this is a tool tip, not a regression, which is used to label functions and buttons which is used for vocalisation by screenreader. This is helpful for users with accessibility issues so removing it might cause issues for them. 

Closing  the issue.

**Closed by ubbabeck** 2023-05-08 13:02 UTC
