### ISSUE TITLE
[Podcast] Speed resets in first seconds

### ISSUE THREAD

**Issue by MaxHillebrand** [breez/breezmobile#510] opened 2021-06-22 19:41 UTC
When starting to play a podcast for the first time when opening breez, then the speed of playback is `1x` for about 1 second, after which it speeds up gradually to the previously set speed.

~Fwiw, right now [the latest](https://github.com/breez/breezmobile/releases/tag/0.12.lnd) Breez keeps crashing for me, so maybe this only happens after a crash...?~
It is not crash related, I can reproduce even when manually exiting and force closing Breez...

**Comment by erdemyerebasmaz** [comment] 2024-05-16 21:09
This issue appears to be fixed.
Closing, can't reproduce.

**Closed by erdemyerebasmaz** 2024-05-16 21:09 UTC
