### ISSUE TITLE
Bug: transaction ok but it didn't appear on Breez transaction list

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#233] opened 2019-12-15 16:03 UTC
Hi, see the steps:

1- I created an invoice of 100 sats on Phoenix
2- I tried to pay the invoice on Breez and appeared the processing payment popup for some minutes, so I closed Breez app.
3- I reopened Breez and on Transaction list appeared the transaction as pending and the backup icon on top right appeared too.
4- I went to Phoenix and saw that I received the transaction.
5- I went to Breez and the pending transaction disappeared but didn't appear as complete on transaction list. 

![photo5165745282628036708](https://user-images.githubusercontent.com/1178856/70865333-23a88680-1f3b-11ea-876c-74d2072072d3.jpg)

![photo5165995026386364558](https://user-images.githubusercontent.com/1178856/70865336-299e6780-1f3b-11ea-9cd9-edb289b4e304.jpg)

![photo5165745282628036709](https://user-images.githubusercontent.com/1178856/70865340-30c57580-1f3b-11ea-8dd4-10e81b2c74b7.jpg)

[lnd.log](https://github.com/breez/breezmobile/files/3965123/lnd.log)

**Comment by bitcoinuser** [comment] 2019-12-15 16:08
I restarted the app again and now appear the 100 sats transaction, but took so many minutes to this happen.

Will attach log here after the transaction appeared on transaction list
[lnd1.log](https://github.com/breez/breezmobile/files/3965128/lnd1.log)

**Comment by roeierez** [comment] 2019-12-15 16:11
At the time the payment succeeded on the receiver it still not successful on the sender end since the sender is waiting for the preimage which may be still stuck along the path.
By observing the logs I see that only after the app restarted your node got the preimage and was able to fully resolve the payment.

**Comment by roeierez** [comment] 2019-12-15 16:32
As for the issue where the pending payment disappeared after restart and only was shown later on the next restart I believe it is related to the way we show payments  in the app.
Right now we synchronize the LND payments into breez db so we will be able to fetch them immediately after restart without the need to wait for LND RPC interface to be ready.
The pending payments are taken from the channel pending htlcs and right now it is queried via the RPC interface.
This behavior creates a gap of several seconds when we show the payments without the pending ones.
We have a plan to change this behavior and get all the payments via directly querying the channeldb and by that we won't need to synchronize nor wait for LND RPC interface to be ready.

**Comment by roeierez** [comment] 2019-12-15 18:00
Update: I reproduced the disappeared transaction by this flow:
1. pay invoice
2. Before the payment succeed, force close breez app.
3. open breez again, the payment will succeed and be shown in the command "listpayments" but not on the UI. Only after restart it will be shown.

The reason is because when closing the app in the middle of a payment the payment enters an "in-flight" status.
Then when restart the payment is resumed and succeed but there is no event (that I am aware of) in LND that triggers a UI refresh to get the new succeeded payment.
There isn't a problem if the payment succeed before the restart as we refresh the UI when the comand "SendPayment" finished.

**Comment by roeierez** [comment] 2020-01-25 20:22
Fixed in latest update when we introduced also better support for hold invoice.

**Closed by roeierez** 2020-01-25 20:22 UTC
