### ISSUE TITLE
When Breez stay closed for a long time,  creating an invoice, the popup close automatically before show qrcode

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#561] opened 2021-08-31 14:50 UTC
Hi,

When Breez stay closed for a long time,  creating an invoice, the popup close automatically before show qrcode. So the user needs to proceed with creating an invoice more than one time.

OS: Android.

**Comment by kingonly** [comment] 2021-08-31 14:52
I think the app just closes.

**Comment by tlindi** [comment] 2023-01-18 23:40
It is now showing "Syncing" instead of closing while creating invoice. At least on PoS with. Isn't it?

**Comment by erdemyerebasmaz** [comment] 2024-05-16 21:25
> It is now showing "Syncing" instead of closing while creating invoice. At least on PoS with. Isn't it?
Yes and this is true for "Receive via Invoice" as well.

Tested with a node that was not synced for a long time, can't reproduce. Closing.

**Closed by erdemyerebasmaz** 2024-05-16 21:25 UTC
