### ISSUE TITLE
Wrong colour of error message

### ISSUE THREAD

**Issue by ubbabeck** [breez/breezmobile#1089] opened 2023-03-15 14:44 UTC
On the latest android production build the error is red, but is supposed to be yellow like the left one. The iOS testflight version seems to be fine.

![red-yellow-error](https://user-images.githubusercontent.com/36157890/225344797-22af3c0e-7122-415b-a1d1-b7a2c7a82ff6.png)

**Comment by erdemyerebasmaz** [comment] 2023-03-15 19:12
Can't reproduce.

**Comment by kingonly** [comment] 2023-03-15 19:34
@erdemyerebasmaz this is production app on my Android device. Please verify. 
![Screenshot_2023-03-15-21-33-38-94_73a31df444cba46df764485ac1a8c3ef](https://user-images.githubusercontent.com/31890660/225423015-f9985724-22bb-4485-906e-c55d8787b5ca.jpg)

**Comment by erdemyerebasmaz** [comment] 2023-03-15 19:57
@kingonly Ah, my bad, I had tested with online build.
Either way, the issue seems to be resolved with new package.

**Closed** 2023-03-15 20:02 UTC

**Comment by kingonly** [comment] 2023-03-15 20:16
Thank you 🙏❤️
