### ISSUE TITLE
Minor bug after keysend payment

### ISSUE THREAD

**Issue by bitcoinuser** [breez/breezmobile#396] opened 2020-10-31 18:51 UTC
Steps to reproduce:

1- Copy a node id to send a payment
2- Use Breez Paste Node ID option
3- Do the payment. 
4- Payment is done. 
5- Now minimize Breez and turn off the phone screen
6- Wait some minutes and turn on the screen again and open breez.

Appear this:

![photo_2020-10-31_15-50-28](https://user-images.githubusercontent.com/1178856/97787430-e53aab00-1b90-11eb-8efd-9df19b2a58b5.jpg)

**Comment by erdemyerebasmaz** [comment] 2024-05-16 20:57
Closing, can't reproduce anymore.

**Closed by erdemyerebasmaz** 2024-05-16 20:57 UTC
