### ISSUE TITLE
Podcasts don't auto-refresh

### ISSUE THREAD

**Issue by genen** [breez/breezmobile#456] opened 2021-03-31 23:02 UTC
In iOS version at least, when I am subscribed to a podcast, only the episodes which were online the previous time I listened are showing. I need to manually pull down on that podcast to do a refresh of its RSS feed to see any new episodes.  

Is this by design or a bug? Generally, when a podcast app lets you subscribe to podcasts, it will at minimum keep the feed refreshed and optionally auto-download new episodes. I think the same type of functionality would be expected by users here as well.

**Comment by kingonly** [comment] 2021-03-31 23:04
It's by design, but the library author is working on a better solution.

**Comment by kingonly** [comment] 2021-06-29 16:47
This partially fixed in the latest update. What's missing is an indication that's there's a refresh in progress.

**Closed** 2021-09-09 10:26 UTC
