### ISSUE TITLE
POS does not create a QR/invoice

### ISSUE THREAD

**Issue by Nackoo2000** [breez/breezmobile#1285] opened 2024-05-12 06:27 UTC
When I try to create an invoice in the POS interface there are problems.

https://github.com/breez/breezmobile/assets/127208515/7c5fd835-3e49-4d2c-9441-78877104da83

[breez.logs (16).zip](https://github.com/breez/breezmobile/files/15285287/breez.logs.16.zip)

**Comment by erdemyerebasmaz** [comment] 2024-05-13 16:41
Can't reproduce.

**Comment by Nackoo2000** [comment] 2024-05-15 06:43
1. Try to go to the keypad first.
2. Enter an amount
3. Click charge

Sometimes when entering the items first the invoice appears - I am not sure where is the difference but when entertaining in the keypad first - the problem is consistent.

**Comment by Nackoo2000** [comment] 2024-05-15 10:39
1. Open app to POS interface
2. Open Keypad
3. Force close app - for Android closing the app with both ways (triangle and square buttons) reproduces the problem
4. Open app - it loads directly to the POS Keypad
5. Enter an amount
6. Click charge and the invoice does not generate

iOS logs:
[breez.logs (20).zip](https://github.com/breez/breezmobile/files/15320055/breez.logs.20.zip)

Android logs:
[breez.logs (21).zip](https://github.com/breez/breezmobile/files/15320091/breez.logs.21.zip)

**Comment by erdemyerebasmaz** [comment] 2024-05-16 23:29
Closing as per the discussion on Slack channel.

**Closed by erdemyerebasmaz** 2024-05-16 23:29 UTC
