### ISSUE TITLE
Backup: `Don't prompt again` not working 

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1116] opened 2023-04-12 08:45 UTC
selecting `Don't prompt again` doesn't do/change anything

remove it (& always display warning triangle when no backup) or make it work :)
![IMG_20230412_103744](https://user-images.githubusercontent.com/93143998/231402055-df980de6-1a98-4b8f-b385-7767926c2e47.jpg)

**Comment by MarnixCroes** [comment] 2023-04-12 08:46
long time bug, I couldn't find any related GH issues

**Comment by kingonly** [comment] 2023-04-12 08:47
@ademar111190 please follow up

**Comment by ademar111190** [comment] 2023-04-13 12:09
Hi @MarnixCroes thank you for the report.
I couldn't reproduce the bug, is it possible for you to record the dialog being prompt when the option is enabled? That could help me a lot 🙏

**Comment by MarnixCroes** [comment] 2023-04-13 12:50
> Hi @MarnixCroes thank you for the report. I couldn't reproduce the bug, is it possible for you to record the dialog being prompt when the option is enabled? That could help me a lot pray

https://user-images.githubusercontent.com/93143998/231759592-599b213f-040b-4695-abb5-fd7a8258a3ae.mp4


@ademar111190 
FYI, the recording is on GrapheneOS, but it also happens on (Samsung) One UI.
It's not related that it's a new empty wallet, I created this one just for the recording, it also happens on long time used wallets with funds.

**Comment by kingonly** [comment] 2023-04-13 13:51
If you mean the warning icon doesn't go away - this is by design. The option is to disable the dialog prompt after payments.

**Comment by MarnixCroes** [comment] 2023-04-13 13:58
I see, makes sense thx, 
What made question is that:
When the `Don't prompt again` isn't check marked, there is no difference in behavior? (after restarting Breez)
or when is the prompt supposed to show up?

**Comment by kingonly** [comment] 2023-04-13 17:21
If the prompt is unchecked, there should be a promotion after a payment

**Comment by MarnixCroes** [comment] 2023-04-13 18:16
> If the prompt is unchecked, there should be a promotion after a payment

hmm, that doesn't happen 😅

**Comment by kingonly** [comment] 2023-04-13 19:11
> > If the prompt is unchecked, there should be a promotion after a payment
> 
> hmm, that doesn't happen 😅

Can you share a video?

**Comment by MarnixCroes** [comment] 2023-04-14 10:23
> Can you share a video?

Nothing happens:
- prompt is unchecked
- generate invoice
- `Payment received!`
- click to confirm animation

that's it, there is no prompt after (as supposed to?)

**Comment by ademar111190** [comment] 2024-01-03 09:11
Closing as it was fixed by #1192

**Closed by ademar111190** 2024-01-03 09:11 UTC
